
var Element = require('/home/mjennings/pagebuilder/html.js')
var coms = require('./components.js')
var temp = require('./templates.js')

module.exports.projects = function() {
  var content = new Element('div').content(
    new Element('p').content(
      "Here are some things I've been working on lately:"
    ),
    new Element('p').content(
      coms.link("Deftly", 'deftly', 'up'),
      ", a website I built to display some of my generative sketches.",
      "<br/>",
      coms.link("Electrodynamics", 'electrodynamics', 'up'),
      ", an Android app that generates lightning bolt visuals.",
      "<br/>",
      coms.link("A porfolio website", 'charlibeck', 'up'),
      " for an illustrator, Charli Beck.",
      "<br/>"
    )
  )
  return temp.linkedContainer('projects', content, false, true, 100)
}

module.exports.deftly = function(){
  var div = new Element('div').content(
    new Element('p').content(
      coms.outLink('Deftly', 'http://www.deftsketches.com', true)
    ).style(coms.font(1.3)),
    new Element('p').content(
      'Deftly is a website I built to display some of my generative sketches. ',
      'You can check it out at ',
      coms.outLink("deftsketches.com", 'http://www.deftsketches.com'),
      '. ',
      "It's a relatively simple single-page site, but features seamless \
       transitions from sketch to sketch."
    ),
    new Element('p').content(
      "I don't have a Macbook to test on, so it may not not run well on Safari."
    ),
    new Element('p').content(
      "You can take a look at the code on ",
      coms.outLink("Github", "https://github.com/jenningsm/deft"),
      "."
    )
  )
  return temp.linkedContainer('deftly', div, true, false, 100)
}

module.exports.electrodynamics = function(){
  var div = new Element('div').content(
    new Element('p').content(
      coms.outLink('Electrodynamics', 'https://play.google.com/store/apps/details?id=com.mjngs.gllightning', true)
    ).style(coms.font(1.3)),
    new Element('p').content(
      'Electrodynamics is a very simple Android app I built that generates lightning bolt visuals when the screen is touched. \
       You can download it for free from the ',
      coms.outLink("play store", 'https://play.google.com/store/apps/details?id=com.mjngs.gllightning'),
      "."
    ),
    new Element('p').content(
      'The app was built in Java and uses OpenGL for the graphics.' 
    )
  )
  return temp.linkedContainer('electrodynamics', div, true, false, 100)
}

module.exports.charlibeck = function(){
  var div = new Element('div').content(
    new Element('p').content(
      coms.outLink('Charli Beck', 'http://www.mjngs.com/cb', true)
    ).style(coms.font(1.3)),
    new Element('p').content(
      'A portfolio site I built for an illustrator. \
       You can check it out at ',
      coms.outLink("mjngs.com/cb", 'http://www.mjngs.com/cb'),
      "."
    ),
    new Element('p').content(
      "This was the first full website I'd ever built, and I think there's a lot wrong with it. However, I've learned a lot since this site \
       and I think it gives a sense of my trajectory."
    ),
    new Element('p').content(
      "You can take a look at the code on ",
      coms.outLink("Github", "https://github.com/jenningsm/cb"),
      "."
    )
  )
  return temp.linkedContainer('charlibeck', div, true, false, 100)
}

module.exports.portfolio = function(){
  var div = new Element('div').content(
    new Element('p').content(
      coms.underline('This Site', true)
    ).style(coms.font(1.3)),
    new Element('p').content(
      "I only include this page to make a note about the css and html of this site. If you look at them, they look really \
       ugly, with a large number of tiny classes with incomprehensible names. The reason for this is that the html and css \
       were generated by a tool I'm developing. The code that generated the html and css is much more ordered than the html \
       and css themselves."
    ),
    new Element('p').content(
       "Unfortunately, I haven't yet documented this tool, as it's still changing, but if you take a look \
       at the ",
       coms.outLink("code", "https://github.com/jenningsm/portfolio/blob/master/k.js"),
       " for this site, you might be able to get a rough idea what's going on."
    )
  )
  return temp.linkedContainer('portfolio', div, true, false, 100)
}

